"""Added version field to PersistentAppInformationModel

Revision ID: 56cd26f9a91e
Revises: 864c4cd9b8ef
Create Date: 2023-08-28 10:26:21.989600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56cd26f9a91e'
down_revision = '864c4cd9b8ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persistent_app_information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persistent_app_information', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
