"""Added PersistentAppInformationModel

Revision ID: 864c4cd9b8ef
Revises: ce2192a00d0a
Create Date: 2023-08-28 01:49:46.203736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '864c4cd9b8ef'
down_revision = 'ce2192a00d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persistent_app_information',
    sa.Column('app_slug', sa.String(), nullable=False),
    sa.Column('title_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('app_slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persistent_app_information')
    # ### end Alembic commands ###
